### ISSUE TITLE
Cannot get it working?

### ISSUE THREAD

**Issue by vans163** [okeuday/cpg#7]
Using elixir I added :cpg to applications in the mix. Tried both with just calling :reltool_util.application_start(:cpg), and having it in applications and calling.

```elixir
:application.which_applications()
[...
 {:cpg, 'CloudI Process Groups', '1.5.1'}
]
```
I then try
```elixir
iex(dev@1.1.1.1)4> :cpg.which_groups                
** (exit) exited in: :gen_server.call(:cpg_default_scope, :which_groups)
    ** (EXIT) no process
    (stdlib) gen_server.erl:204: :gen_server.call/2
```

**Comment by okeuday** [comment]
The same sequence works for me in the Erlang shell:

    1> reltool_util:application_start(cpg).
    ok
    2> cpg:which_groups().
    []
    3> application:get_all_env(cpg).
    [{group_storage,trie},
     {scope,[cpg_default_scope,groups_scope1,groups_scope2]},
     {included_applications,[]},
     {node_type,visible}]

You should check what it says for env when you attempt to run it.  Also, start sasl before attempting that sequence to make sure nothing is crashing.  Erlang/OTP and Elixir version information would help make it clearer what you are testing.

**Comment by vans163** [comment]
Okay so this is what I am doing.

```elixir
mix new cpgtest
#mix.exs
  defp deps do
    [{:cpg, github: "okeuday/cpg"}]
  end
mix deps.get
mix deps.compile
iex -S mix

> :reltool_util.application_start(:cpg)
:ok
> :cpg.which_groups()
** (exit) exited in: :gen_server.call(:cpg_default_scope, :which_groups)
    ** (EXIT) no process
    (stdlib) gen_server.erl:204: :gen_server.call/2

**Comment by okeuday** [comment]
Works fine for the versions you are using (Elixir 1.2.6 with Erlang/OTP 18.3):

    $ iex -pz deps/trie/ebin -pz deps/reltool_util/ebin -pz deps/quickrand/ebin -pz ebin
    Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [kernel-poll:false]
    
    Interactive Elixir (1.2.6) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> :reltool_util.application_start(:cpg)
    :ok
    iex(2)> :cpg.which_groups()
    []

I used rebar2 to compile cpg and test it in the repository, so this may be a problem using mix.

**Comment by vans163** [comment]
Ah. Is elixirs mix supported then?  I just see the mix.exs included in the repo and automatically assume it is.  I am not sure how to build the project using rebar2 when elixir wants you to use mix.  For example building it separately using rebar2 then doing a mix deps.update/clean then manually using rebar2 again is not a comfortable solution.

**Comment by okeuday** [comment]
@vans163 mix has been used to publish hex packages, due to having that functionality before rebar3.  mix should know to use rebar2 or rebar3 with projects that use either, and it may be simpler to use the hex package instead.

**Comment by okeuday** [comment]
@vans163 When mix builds, it is excluding the `env` field for an unknown reason.  That should be a bug, since normally the `.app.src` file provides `env` default values.

**Comment by vans163** [comment]
Awesome.
