### ISSUE TITLE
cpg doesn't gracefully handle upgrading between versions

### ISSUE THREAD

**Issue by AeroNotix** [okeuday/cpg#8]
When cpg is already released and running with distributed erlang, upgrading between versions and doing a rolling release doesn't work as it should since the internal state has changed between versions.

Upgrading from v1.3.1 to master (v1.5.1) exhibits this issue.

Perhaps consider these situations when modifying internal state?

**Comment by okeuday** [comment]
Due to the addition of `group_storage` in the application env settings, you would need to make sure the `#state{groups = Groups}` would become `#state{groups = {trie, Groups}}` during the update from `v1.3.1`.
